CREATE TABLE CURRENCY_TRANSLATION(
    ID VARCHAR(36) PRIMARY KEY,
    CODE VARCHAR(10),
    NAME VARCHAR(30),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) DEFAULT 'system',
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) DEFAULT 'system'
);
ALTER TABLE CURRENCY_TRANSLATION ADD CONSTRAINT CODE_UNIQUE UNIQUE(CODE);

